### PR TITLE
Fixes for AutoPkg 2.0

### PR DESCRIPTION
**Pull request by andrewvalentine**
Errors occurring when running these with AutoPkg 2.0. These fixes should resolve.

### CODE REVIEW

**Comment by geoffklee** [comment]
Many thanks for this! I don't have any way to test it right now, but happy to merge it if you've tested it. Re removal of the comments - are these no longer supported, or are you just suggesting they're unnecessary? (hah - while writing this I discovered that you can use XML comment syntax in these text fields and they're visible only in edit mode!) <script>alert('hmm...')</script>

**Comment by andrewvalentine** [comment]
Oh...bother. I didn't mean to remove those comments. They're still useful and should remain! I'll revert the changes in my fork, recommit, and raise a new PR. I'll close this one when I've done that successfully.

**Comment by andrewvalentine** [comment]
Closing this to open new PR

**Comment by andrewvalentine** [comment]
See https://github.com/UoE-macOS/autopkg-recipes/pull/13

**Pull request closed without merging**
